name: Rust

on:
  workflow_dispatch:
     inputs:
       version:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Checkout code from other repository
      uses: actions/checkout@v4
      with:
        repository: https://github.com/mike-engel/jwt-cli.git
        ref: main
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        target: aarch64-unknown-linux-gnu
        override: true
    - uses: actions-rs/cargo@v1
      with:
        use-cross: true
        command: build
        args: --target aarch64-unknown-linux-gnu
    - name: Directory
      run: ls -lrt
